# Generated by Django 5.2.17 on 2026-10-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp_id', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('cover', models.CharField(blank=True, max_length=300)),
                ('published_at', models.DateTimeField()),
                ('status', models.CharField(default='publish', max_length=20)),
                ('category', models.CharField(default='Corporate News', max_length=100)),
            ],
            options={
                'ordering': ('-published_at', 'title'),
            },
        ),
    ]
